### ISSUE TITLE
Filter with empty Q object doesn't work as expected

### ISSUE THREAD

**Issue by tprestegard** [stphivos/django-mock-queries#102]
Using an empty `Q` object in a Django queryset results in the full queryset being returned:
```
In [2]: User.objects.all().count()
Out[2]: 4827

In [3]: User.objects.filter(Q()).count()
Out[3]: 4827

In [4]: User.objects.filter(~Q()).count()
Out[4]: 4827

In [5]: User.objects.exclude(Q()).count()
Out[5]: 4827

In [6]: User.objects.exclude(~Q()).count()
Out[6]: 4827
```

This seems to work as expected for `exclude()`, but not for `filter()`:
```
In [9]: n1 = MockModel(mock_name='item 1', pk=1)
In [10]: n2 = MockModel(mock_name='item 2', pk=2)
In [11]: mockset = MockSet(n1, n2)

In [12]: mockset.count()
Out[12]: 2

In [13]: mockset.filter(Q()).count()
Out[13]: 0

In [14]: mockset.filter(~Q()).count()
Out[14]: 0

In [15]: mockset.exclude(Q()).count()
Out[15]: 2

In [16]: mockset.exclude(~Q()).count()
Out[16]: 2
```
However, I think it only works as expected for `exclude()` because `filter()` is returning 0.

This is a problem in cases where you are constructing a `Q` object dynamically and it can sometimes end up empty.  I've spent a few hours trying to fix this but haven't gotten there completely.  Part of the process was trying to simplify the logic by converting any lookups by attributes to use Q objects (i.e., `filter(x=1, y=2)` -> `filter(Q(x=1, y=1))`).  Part of the issue is that this conversion causes filtering on `MockSet`s with actual in-memory Django model instances to fail because it uses `django_mock_queries.utils.merge`, which tries to hash them, and fails since they don't have a PK.

I don't know if I'll be able to finish this, but I'll add a [link](https://github.com/stphivos/django-mock-queries/compare/master...tprestegard:fix_filter_with_empty_q) to my current branch in case it's useful.

**Comment by shinneider** [comment]
@stphivos, close this issue, is already fixed.
