### ISSUE TITLE
Add support for Django 3

### ISSUE THREAD

**Issue by leovanzella** [stphivos/django-mock-queries#104]
Hi,

I see in the requirements/core.txt that Django is limited to version 2. What could be done so Django 3.0 can be supported?

**Comment by adamghill** [comment]
I spent a little time looking into Django 3 support and created https://github.com/stphivos/django-mock-queries/pull/107 which I _think_ works. I have very limited experience with the internal Django db code, though.

**Comment by leovanzella** [comment]
That's great @adamghill, I'll take a look and see if I can contribute so.

**Comment by felippemr** [comment]
Hey folks, I saw that the above PR for django 3 has been merged. Does it make sense to publish a new version of django-mock-queries?(Maybe 2.1.4 ?)

**Comment by stphivos** [comment]
Done :)
