### ISSUE TITLE
list() not supported in MockSet

### ISSUE THREAD

**Issue by LucasGlobSing** [stphivos/django-mock-queries#191]
![image](https://github.com/user-attachments/assets/99ce4244-c71b-4459-9552-3f6a41195834)

I was trying to convert a values_list to a list and while debugging I ended up finding that converting MockSet to a list is not possible.

**Comment by stefan6419846** [comment]
I just tried with the latest release and cannot reproduce this (and honestly would have been surprised as well):

```
>>> from django_mock_queries.query import MockSet
>>> my_mock_set = MockSet()
<MockSet spec='QuerySet' id='139728982611792'>
>>> list(my_mock_set)
[]
>>> 
```

Could you please provide some more details on your setup to allow further analysis and actual reproduction?

**Comment by lucassing** [comment]
Somehow is now working, maybe I made a mistake while debugging. Thanks for the quick response.
