### ISSUE TITLE
AND operator is not handled properly causing random tests

### ISSUE THREAD

**Issue by zuzelvp** [stphivos/django-mock-queries#60]
I will try to create a PR but reporting the issue before that just in case. At https://github.com/stphivos/django-mock-queries/blob/master/django_mock_queries/query.py#L68

If all the results of previous childs are empty except for the last child the result of the last child is returned instead of the intersection.

**Comment by zuzelvp** [comment]
Added a test that fails due to this bug 

______________________________________________ TestQuery.test_query_filters_items_by_q_object_or_and ______________________________________________

self = <tests.test_query.TestQuery testMethod=test_query_filters_items_by_q_object_or_and>

    def test_query_filters_items_by_q_object_or_and(self):
        item_3 = MockModel(mock_name='#3', foo=3, bar='b')

        self.mock_set.add(item_3)
        results = list(self.mock_set.filter(Q(bar='b', foo=1)))

>       assert item_3 not in results
E       AssertionError: assert #3 not in [#3]

tests/test_query.py:85: AssertionError

**Comment by stphivos** [comment]
This bug must have caused some confusions.. Thanks!
