### ISSUE TITLE
values().distinct()fails with TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by zuzelvp** [stphivos/django-mock-queries#65]
Will try to fix in a PR.

**Comment by zuzelvp** [comment]
___________________________________________________________________________________ TestQuery.test_query_values_distinct ___________________________________________________________________________________

self = <tests.test_query.TestQuery testMethod=test_query_values_distinct>

    def test_query_values_distinct(self):
        item_1 = MockModel(foo=1, mock_name='item_1')
        item_2 = MockModel(foo=2, mock_name='item_2')
        item_3 = MockModel(foo=3, mock_name='item_3')

        self.mock_set.add(item_2, item_3, item_1, item_3)
>       results = list(self.mock_set.values('foo').distinct().order_by('foo'))

tests/test_query.py:544:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/py35-dj111/lib/python3.5/site-packages/mock/mock.py:1062: in __call__
    return _mock_self._mock_call(*args, **kwargs)
.tox/py35-dj111/lib/python3.5/site-packages/mock/mock.py:1128: in _mock_call
    ret_val = effect(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def distinct():
>       results = set(items)
E       TypeError: unhashable type: 'dict'

django_mock_queries/query.py:160: TypeError

**Comment by zuzelvp** [comment]
Hmm, now I need support for distinct(*fields) I may try to update this PR to allow it

**Comment by stphivos** [comment]
Thanks, the PR looks good. Shall I wait for this update or we merge it later?

**Comment by zuzelvp** [comment]
@stphivos just made the update for the .distinct(*fields) it is running tests now.

**Comment by stphivos** [comment]
Awesome, merged the PR thanks!
