### ISSUE TITLE
Support for Django 2.0

### ISSUE THREAD

**Issue by tnedev** [stphivos/django-mock-queries#69]
Hi, 

What needs to be done for this app to support Django 2.0?

**Comment by zuzelvp** [comment]
I don't know if @stphivos already tried or not, but I would start by adding Django 2.0 here and making the tests pass with the python/django version that you need https://github.com/stphivos/django-mock-queries/blob/master/tox.ini#L19

**Comment by stphivos** [comment]
Hi, I created PR #72 to support Django 2.0.x.

**Comment by stphivos** [comment]
Published just now as [v1.0.7](https://pypi.python.org/pypi/django_mock_queries) on pypi.
