### ISSUE TITLE
Breaking changes in 2.1.2: ignored filtered elements

### ISSUE THREAD

**Issue by dannywillems** [stphivos/django-mock-queries#96]
Hi,

Seems there is a breaking change in the filter implementation, maybe introduced 08b5d769c5c797968f3a8c3db68173324a01162f.

I cannot reproduce with a simple example, but seems some items are ignored while using filter on a mocked QuerySet, even there should be filtered. Downgrading to 2.1.1 works.

I suppose it is when the value is an integer or any other type. You only want to check it is not None, not just if the value is `True`. I would suggest changing it in `if first is not None`

**Comment by dannywillems** [comment]
See #97

**Comment by stphivos** [comment]
Thanks! Added a [test](https://github.com/stphivos/django-mock-queries/commit/d4a1166449ecf6425e10fe506267fdb6ace63173) which reproduces this issue. I will be pushing v2.1.3 to PyPI.
